### ISSUE TITLE
Some links broken

### ISSUE THREAD

**Issue by theghost1980** [UdjinM6/dash-bootstrap#1]
Specifically those ones:
Block 618881: Sat Feb 11 00:00:02 UTC 2017 7z (1.2G) **zip ()** SHA256

Block 618331: Fri Feb 10 00:00:01 UTC 2017 7z (1.2G) **zip ()** SHA256

**Comment by UdjinM6** [comment]
Thanks for reporting!

Yes, this happens sometimes. I guess my machine is simply running out of free disk space when I try to create two archives at once. 4d1ca6c should fix it for now.

**Comment by UdjinM6** [comment]
Should be fixed, closing
