### ISSUE TITLE
Update folders in instructions

### ISSUE THREAD

**Issue by Macr0chip** [UdjinM6/dash-bootstrap#2]
A new user was confused by the outdated folders when he tried to install the bootstrap.
Dash -> DashCore
Thanks!

**Comment by UdjinM6** [comment]
I thought I already fixed it in 1071e5d355d7625354ea3785f621d4352e21581f... but I fixed it in the wrong place 🤦‍♂️ will fix again, thanks for reporting! :)

**Comment by UdjinM6** [comment]
Should be fixed by 9d786d0b3a7060afa78632255b4a12916e00ab49, README, however, will be updated on next autoupdate i.e. in ~6h from now.
