### ISSUE TITLE
I get access denied errors when trying to download the testnet bootstrap.dat.zip links.

### ISSUE THREAD

**Issue by craigbroadbear** [UdjinM6/dash-bootstrap#3]
e.g. click the following link in a browser or curl / wget

https://dash-bootstrap.ams3.digitaloceanspaces.com/testnet/2018-04-01/bootstrap.dat.zip

returns
<Error>
<Code>AccessDenied</Code>
<BucketName>dash-bootstrap</BucketName>
<RequestId>tx000000000000000076df9-005ac167c3-bc3e1-ams3a</RequestId>
<HostId>bc3e1-ams3a-ams3</HostId>
</Error>

**Comment by UdjinM6** [comment]
Looks like testnet daemon died. Should be fixed now, pls try the latest file/link https://github.com/UdjinM6/dash-bootstrap#for-testnet

**Comment by UdjinM6** [comment]
Should be fixed, closing.
